server:
  port: 8081
  servlet:
    context-path: /desafio
  
client:
  protocol: http
  host: localhost
  port: 8080
  context: /periodos
  api-path: /api
  
  
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        
management:
  endpoints:
    web:
      base-path: /
      
info:
  app:
    name: desafio-ccarreno
    description: Prueba Técnica
    version: 0.0.1-SNAPSHOT